### ISSUE TITLE
In `generate_graph_from_stochastic_block_model.py`

### ISSUE THREAD

**Issue by guilgautier** [14chanwa/graphsmlProject#2]
You may define your indices with smtg like
```
div, mod = divmod(N, k)
indices = np.repeat(np.arange(k), [div+1 if i<mod else div for i in range(k)])
```

For creating edges of the SBM
- instead of adding an edge to the Graph object potentially often, you should append an edge `(i,j)` to an list of edges and then pass it to the graph object with
[`add_edges_from`](https://networkx.github.io/documentation/networkx-1.10/reference/generated/networkx.Graph.add_edges_from.html#networkx.Graph.add_edges_from)
- There might be a more Pythonic (list comprehension) way to define the list of edges without the 2 nasty for loops and which would be more efficient for `N` large

**Comment by 14chanwa** [comment]
Managed to remove one of the 2 loops for edge generation ; it might be possible to remove the other loop using bidimensional arrays (todo)
